on:
  push:
    branches: [ 'main' ]

jobs:
  proxy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build project
        run: ./gradlew jar
      - name: Deploy to remote servers
        run: |
          sh /home/cloud/scripts/services/github/actions/deploy.sh build/libs/proxy.jar